name: Publish image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: |
          Either a semantic version or "next" if creating an ephemeral release
          from the head of the main branch.

jobs:
  asd:
    runs-on: ubuntu-latest
    steps:
      - name: Create tags
        id: create_tags
        run: |
          image_name="what"

          if [ "${{ inputs.version }}" = "next" ]; then
            echo "tags=${image_name}:next" >> $GITHUB_OUTPUT
            echo "ref=refs/heads/main"
          else
            echo "tags=${image_name}:latest,${image_name}:${{ inputs.version }}" >> $GITHUB_OUTPUT
            echo "ref=refs/tags${{ inputs.version }}"
          fi

      - name: Checkout
        uses: actions/checkout@v6

      - name: Verify correct checkout
        run: |
          cat galaxy.yml

      - name: Verify tags
        run: |
          echo ${{ steps.create_tags.outputs.tags }}

      # Acual publish here.
